---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - php
    checks:
      Similar code:
        enabled: false
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: "tests/phpmd.xml"
  phpcodesniffer:
    enabled: true
    config:
      standard: "Wordpress-Extra"
    checks:
      # Disable: Class file names should be based on the class name with "class-" prepended.
      WordPress Files FileName InvalidClassFileName:
        enabled: false
      # Disable: Blank line found after control structure
      WordPress WhiteSpace ControlStructureSpacing BlankLineAfterEnd:
        enabled: false
      # Disable: Expected 1 space after closing brace; newline found
      Squiz ControlStructures ControlSignature SpaceAfterCloseBrace:
        enabled: false
      # Disable: Inline control structures are not allowed
      Generic ControlStructures InlineControlStructure NotAllowed:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/*
- bin/*
# Local
- vendor/*
