version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 5
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 1000
  method-complexity:
    enabled: true
    config:
      threshold: 50 # Only check extreme cases
  method-count: # Done in PHPMD
    enabled: false
    config:
      threshold: 20
  method-lines: # Done in PHPMD
    enabled: false
    config:
      threshold: 100
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: false
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
plugins:
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: "tests/phpmd.xml"
  phpcodesniffer:
    enabled: true
    config:
      standard: "Wordpress-Extra"
    checks:
      # Disable: The $domain arg must be a single string literal, not "". Sniff not working (class constant).
      WordPress WP I18n NonSingularStringLiteralDomain:
        enabled: false
      # Disable: Class file names should be based on the class name with "class-" prepended.
      WordPress Files FileName InvalidClassFileName:
        enabled: false
      # Disable: When an array uses associative keys, each value should start on a new line.
      WordPress Arrays ArrayDeclarationSpacing AssociativeKeyFound:
        enabled: false
      # Disable: Blank line found after control structure.
      WordPress WhiteSpace ControlStructureSpacing BlankLineAfterEnd:
        enabled: false
      # Disable: Expected 1 space after closing brace; newline found.
      Squiz ControlStructures ControlSignature SpaceAfterCloseBrace:
        enabled: false
      # Disable: Inline control structures are not allowed.
      Generic ControlStructures InlineControlStructure NotAllowed:
        enabled: false
exclude_patterns:
- "tests/*"
- "bin/*"
# Local
- "vendor/*"
